import React from 'react';
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { ResultsHeader } from '../src/components/dashboard/ResultsHeader';
import { LanguageProvider } from '../src/i18n/LanguageContext';

describe('ResultsHeader Gemini AI Badge', () => {
  it('renders a distinct Gemini AI badge when report is generated by Gemini', () => {
    render(
      <LanguageProvider defaultLanguage="az">
        <ResultsHeader
          reportId="agro-gemini-1791552078040"
          source="gemini"
          crop="Pambıq"
          region="Aran"
        />
      </LanguageProvider>
    );

    expect(screen.getByText('Gemini AI ilə Təhlil Edildi')).toBeInTheDocument();
  });

  it('renders English Gemini AI badge when language is en', () => {
    render(
      <LanguageProvider defaultLanguage="en">
        <ResultsHeader
          reportId="agro-gemini-1791552078040"
          source="gemini"
          crop="Cotton"
          region="Aran"
        />
      </LanguageProvider>
    );

    expect(screen.getByText('Powered by Gemini AI')).toBeInTheDocument();
  });
});
